### ISSUE TITLE
Every time player open vault new vault record in the database is created (MySQL)

### ISSUE THREAD

**Issue by gegtor** [RiceField-Plugins/RFVault#1]
Hi while testing your plugin I found a lot of issues and I will split report anything I find to bring this plugin to production-ready state

As per title
<img width="698" alt="Screenshot 2021-12-10 at 02 16 47" src="https://user-images.githubusercontent.com/10978723/145500858-0b6528f8-1f3a-49e8-b0f4-94b8935bde2f.png">

Duplicate vault records are created for the same user every time he opens vault

**Comment by BarehSolok** [comment]
this issue has been fixed by now
