### ISSUE TITLE
UI lags when opening vault

### ISSUE THREAD

**Issue by gegtor** [RiceField-Plugins/RFVault#2]
When opening vault a noticeable lag occurs on the client (UI freezes) while the plugin is fetching data from the database (around 50-250ms)

And that's with 7 records with around 10 000 on my network the lag would be horrible

Other plugins go around that with first rendering the UI using width and height and then loading items live

**Comment by BarehSolok** [comment]
that's good idea, currently the plugin loads whole items at a time, but i'll have to find a way to handle if player disconnected while loading items

**Comment by BarehSolok** [comment]
this features will be added in the next version
