### ISSUE TITLE
Plugins should favour the biggest vault user has access to

### ISSUE THREAD

**Issue by gegtor** [RiceField-Plugins/RFVault#3]
The plugin opens vaults in their order in the config

Other vault plugins open biggest vault user has access to by default

Opening the biggest vault is more intuitive since usually, that's what you want to use, and either way, if you want to use a small vault you can set it via command

**Comment by BarehSolok** [comment]
this is why `/vset` command exists, you can set specified Vault as your default in `/vault` command
